version: '3.0'

services:
  grafana:
    container_name: '{{ pluginId }}'
    platform: "linux/amd64"
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-{{~grafanaImage~}} }
        grafana_version: ${GRAFANA_VERSION:-{{~grafanaVersion~}} }
    ports:
      - 3000:3000/tcp
    volumes:
    {{#if monoRepo}}
      {{#each pluginNames as |name|}}
      - ./packages/{{name}}/dist:/var/lib/grafana/plugins/{{ name }}
      {{/each}}
    {{else}}
      - ./dist:/var/lib/grafana/plugins/{{ pluginId }}
    {{/if}}
      - ./provisioning:/etc/grafana/provisioning